version: "3.8"

services:
  app:
    build: .
    container_name: ykhoa_app
    environment:
      - MYSQL_HOST=ykhoa_db
      - MYSQL_PORT=3306
      - MYSQL_DB=ykhoa_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - PORT=3000
    volumes:
      - ./:/usr/app
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    image: "mariadb:10.5"
    container_name: ykhoa_db
    environment:
      MYSQL_DATABASE: ykhoa_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./data/mariadb:/var/lib/mysql:delegated
      - ./data/backup:/home/db_backup:delegated
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf:z
    ports:
      - "3308:3306"
  
  phpmyadmin:
    image: library/phpmyadmin
    container_name: ykhoa_phpmyadmin
    tty: true
    depends_on:
     - mysql
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOSTS: ykhoa_db
      PMA_PORT: 3333
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 128M
    ports:
       - '8181:80'


