export * from './AuthController';
// export * from './UserController';
export * from './UploadController';
export * from './CommentControllerr';
export * from './ShopController';
export * from './MedicineController';
export * from './article/CategoryController';
export * from './article/ArticleController';
export * from './auth/RegisterController';
export * from './auth/LoginController';
export * from './auth/ProfileController';
export * from './auth/ForgetPasswordController';
export * from './user/UserController';
export * from './user/DoctorController';
export * from './user/OfficeController';
export * from './user/PhamacryController';